name: Tests

on: 
  pull_request:
  push:
    branches: [main] # code coverage reporting needs to be on main so all PRs can compare against it.

concurrency: # cancel previous workflow run if one exists.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: customerio/mobile-ci-tools/.github/workflows/ios-test.yml@main
    with:
      scheme: 'CioFirebaseWrapper'
      xcresult-name: 'CioFirebaseWrapper.xcresult'
